name: sms-backup-restore

networks:
  sms_backup_restore_network:
    driver: bridge
volumes:
  redis_data: null
  minio_data: null
  dynamodb_data: null
  redpanda: null

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=sms-backup-restore
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb_data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
