name: Update Lambda with New Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create image URL
        id: image_url
        run: |
          echo "ecr_repository_url=${{ secrets.AWS_ECR_REGISTRY_URL }}/${{ vars.ECR_IMAGE_NAME }}" >> "$GITHUB_ENV"
          echo ${{ env.ecr_repository_url }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker_nodejs_demo
          IMAGE_TAG: nodejs_demo_image
        run: |
          docker build -t ${{ vars.ECR_IMAGE_NAME }} .
          docker tag ${{ vars.ECR_IMAGE_NAME }}:latest ${{ env.ecr_repository_url }}:${{ github.sha }}
          docker push ${{ env.ecr_repository_url }}:${{ github.sha }}

      - name: Update Lambda function
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ vars.LAMBDA_FUNCTION_NAME }}
          image_uri: ${{ env.ecr_repository_url }}:${{ github.sha }}
